### ISSUE TITLE
TypeError: Argument 0 does not allow None as a value

### ISSUE THREAD

**Issue by UltraBlackLinux** [arcolinux/archlinux-tweak-tool#1]
Hey there,
I just found out about this wonderful tool on your youtube channel, though running it fails for me:
```
Traceback (most recent call last):
  File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 2254, in <module>
    Gtk.StyleContext.add_provider_for_screen(
TypeError: Argument 0 does not allow None as a value
```
Is this a problem on my side, or are you able to fix this?
Thanks!

**Comment by arcolinuxz** [comment]
We will make ATT available in the beginning on these systems
- updating README of this github

**Comment by UltraBlackLinux** [comment]
> We will make ATT available in the beginning on these systems
> 
>     * updating README of this github

What's ATT?

**Comment by UltraBlackLinux** [comment]
This appears to be a problem with Wayland, see [here](http://arcolinuxforum.com/viewtopic.php?t=1740&start=10)

**Comment by arcolinuxz** [comment]
is it not all a problem with wayland

**Comment by joezak11** [comment]
It does return an object, yet I still get the same error.
```python
In [4]: Gdk.Screen.get_default()
Out[4]: <__gi__.GdkWaylandScreen object at 0x7f96415f10c0 (GdkWaylandScreen at 0x56296dbe4810)>
```

**Comment by arcolinuxz** [comment]
I am not putting any effort into supporting wayland
as long you know that ... you can make your decision

**Comment by UltraBlackLinux** [comment]
apparently this is supposed to fix this exact issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1997
Worked for one person at least.
Gonna try to verify that tomorrow
