### ISSUE TITLE
ATT somehow changed my OS in neofetch and fastfetch from Garuda to ArcoLinux

### ISSUE THREAD

**Issue by PWDSerialgamer07** [arcolinux/archlinux-tweak-tool#12]
I recently installed ATT on Garuda Linux. I started it up and noticed the neofetch settings. So far, all I have done is turn on the "neofetch enabled button" and apply neofetch config. When running neofetch or fastfetch I get this:
[Neofetch]
![image](https://github.com/arcolinux/archlinux-tweak-tool/assets/118306463/d13bbd9b-0b52-4a41-9528-05b4a5f5c46b)
[Fastfetch]
![image](https://github.com/arcolinux/archlinux-tweak-tool/assets/118306463/52cca626-9a80-4dc9-856b-5162c5fc2d1b)
Can anyone help me reset it to Garuda?

**Comment by dr460nf1r3** [comment]
I'd still leave this open even though the problem is solved on your end - it needs to be investigated why this apparently changed the distro info to Arcolinux. Reinstalling `garuda-hooks` just rewrote them to Garuda.

**Comment by sgse** [comment]
Did we like cross posting :thinking:

**Comment by dr460nf1r3** [comment]
We like creating issues at source code repos to get bugs fixed 😋

**Comment by arcolinuxz** [comment]
Remember the button at the button. 
There is always a .bak file.
You can set it back that way.
See video

https://youtu.be/AqvDmp4029M?t=1752

**Comment by dr460nf1r3** [comment]
> Remember the button at the button.
> There is always a .bak file.
> You can set it back that way.

It is easy to reset, yes. But why does it happen in the first place? Considering this is a universal Archlinux Tweak Tool, rebranding to Arcolinux should be considered unacceptable.
