### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by wavic** [arcolinux/archlinux-tweak-tool#6]
Line 59  in  /usr/share/archlinux-tweak-tool/fixes.py  
Can't post the error traceback because I bypassed it by put it in conditional: Do not want to install it again to reproduce it.

```python
if check_cursor_global(lines, "inherits="):
            cursor_theme = check_cursor_global(lines, "Inherits=").split("=")[1]
```
Can't manipulate the cursor themes. Not big deal.
Anyway I have installed Cinnamon and can't change the sddm theme hitting "Apply" btn. 
Iit sais "You need to select desktop and/or theme first" 
I have a desktop theme selected by Themes Cinnamon's tool.

**Comment by arcolinuxz** [comment]
run fix-sddm-conf
