### ISSUE TITLE
Issue installing desktop

### ISSUE THREAD

**Issue by webmaster-exit-1** [arcolinux/archlinux-tweak-tool#7]
### Had an issue installing Plasma Desktop, So I decided to run some testing.

Testing Env.: New Python VENV for each Python Version starting at Python 3.6 to 3.11,
Using New Tarball from Github Archlinux-Tweak-Tool 22.06-74

Test #1 
**Starting the application.**
>    -- 3.6 started but with error
>  ```py
>  invalid literal for int() with base 10: '"15"\n'
>  ```
>  -- 3.7 started but with error
>  ```py
>  invalid literal for int() with base 10: '"15"\n'
>  ```
>  -- 3.8 started but with error
>  ```py
>  invalid literal for int() with base 10: '"15"\n'
>  ```
>  -- 3.9 started but with error
>  ```py
>  invalid literal for int() with base 10: '"15"\n'
> ```
>  -- 3.10 started but with error
>  ```py
>  invalid literal for int() with base 10: '"15"\n'
>  ```
>  -- 3.11 started but with error
>  ```py
>  invalid literal for int() with base 10: '"15"\n'
>  ```

Test #2 
**Installing Plasma Desktop**

Testing Note: 
* Clean venv and new tarball downloaded from github.
* Will update progress every 10 minutes, or until something happens.
* If nothing happens within 30 minutes, the test will be terminated and final error message will be noted.
* Will only be using the latest version of python in a venv, Python 3.11.0

Time of test #2: 10:50:25 p.m. PST

* Clicked Install for Desktop Plasma
* Checkpoint #1 10 minutes. No sign of anything happening.
* Checkpoint #2 20 minutes. No sign of anything happening.
* Checkpoint #3 30 minutes. No sign of anything happening.
* Test Terminated

Final output from termination:

```py
ATT is Closing.
Exception in thread Thread-1 (install_desktop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
```
Observation Notes:
* It appears it broke free of the venv for reasons unknown or do to user error on my behalf.
* From the image I'm providing you can see in my terminal prompt I am clearly using Python 3.11 venv.

![final-testing-output](https://user-images.githubusercontent.com/98633966/199914197-dda330dc-74a1-4d99-9161-3b9c4df2f0b1.png)

Check the discord report channel for this tool because Github added words to my issue, For the checkpoints. Not sure why or what's going on, but it appears as if I have triggered Github's AI Copilot or some sort of markdown syntax thing Github has setup.
Anyways, I just wanted to help out because I love Arcolinux and to show appreciation for all the hard work you all put into this distro.
And most of all, to get this tool working correctly.

**Comment by arcolinuxz** [comment]
You are welcome to ask help on discord.
There are no issues on my several computer systems.

**Comment by arcolinuxz** [comment]
ps your tarbal is OOOOLD
