### ISSUE TITLE
XWayland support

### ISSUE THREAD

**Issue by cold-nagai** [arcolinux/archlinux-tweak-tool#8]
Seems like [people](https://github.com/arcolinux/archlinux-tweak-tool/issues/1) don't know how to run programs with root privileges on Xwayland, so i thought it'd be helpful if you'll add a short [instruction](https://wiki.archlinux.org/title/Running_GUI_applications_as_root#Using_xhost) on how to run ATT on XWayland. 

>Wayland desktops are not supported e.g. Sway/Hyprland/...
```
xhost + local:
archlinux-tweak-tool 
```

**Comment by arcolinuxz** [comment]
that is solved in the meantime
